### PR TITLE
Add attribute selector support

### PR DESCRIPTION
**Pull request by dword-design**
Adds support for attribute selector nesting.

### CODE REVIEW

**Comment by dword-design** [comment]
@jonathantneal Any chance to get this merged?

**Comment by dword-design** [comment]
@jonathantneal Any chance to have this merged?

**Comment by jonathantneal** [comment]
Thank you, @dword-design ! Oh so late, I say...

**Comment by dword-design** [comment]
@jonathantneal Thanks, too bad it's part of the big release since I'm not using Node.js 16 yet :P.

**Pull request merged**
