### PR TITLE
feat: include node 16 and stylelint 14 in deps

### PR DESCRIPTION
**Pull request by benbender**
feat: include node 16 and stylelint 14 in deps

### CODE REVIEW

**Comment by bryanjtc** [comment]
@jonathantneal Can you merge this pr?

**Review by jonathantneal — APPROVED** [review]
This is good and important.

**Comment by MattIPv4** [comment]
👋 @jonathantneal Would it be possible for a new release to be published to NPM that captures this?

**Comment by jonathantneal** [comment]
@MattIPv4, done! https://github.com/csstools/stylelint-use-nesting/releases/tag/4.0.0

**Pull request merged**
